name: fs_service
description: Firestore service tool. Allow developer to get or add documents and collections to the Firestore using service account.
repository: https://github.com/sla-000/fs_service
version: 2.0.0

environment:
  sdk: ^3.3.0

executables:
  fs_service:

dependencies:
  _discoveryapis_commons: ^1.0.6
  args: ^2.4.2
  fs_service_lib:
    path: ./packages/fs_service_lib # todo Point to pub.dev
  get_it: ^7.6.4
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  http: ^1.1.0
  logging: ^1.2.0
  meta: ^1.10.0

dev_dependencies:
  check_coverage: ^0.0.5
  melos: ^3.2.0
  mocktail: ^1.0.1
  test: ^1.21.0

